services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: web
    ports:
      - "3000:3000"
    environment:
      # Exposed to the frontend, update if you change Strapi host/port
      NEXT_PUBLIC_API_URL: http://localhost:1337
      # Ensure Next dev server binds to all interfaces in container
      HOST: 0.0.0.0
      PORT: 3000
    command: ["yarn", "dev", "-H", "0.0.0.0", "-p", "3000"]
    volumes:
      # Mount local source for hot-reload
      - ./web:/app
      # Use a container-only volume for node_modules to avoid host conflicts
      - web_node_modules:/app/node_modules
    depends_on:
      - content

  content:
    build:
      context: ./content
      dockerfile: Dockerfile.dev
    container_name: content
    ports:
      - "1337:1337"
    environment:
      # Strapi required secrets (use your own secure values for real projects)
      NODE_ENV: development
      APP_KEYS: "dev-app-key-1,dev-app-key-2"
      API_TOKEN_SALT: "dev-api-token-salt"
      ADMIN_JWT_SECRET: "dev-admin-jwt-secret"
      TRANSFER_TOKEN_SALT: "dev-transfer-token-salt"
      # Database settings (sqlite is default using config/database.ts)
      DATABASE_CLIENT: sqlite
    volumes:
      # Mount local source for hot-reload
      - ./content:/srv/app
      # Use a container-only volume for node_modules to avoid host conflicts
      - content_node_modules:/srv/app/node_modules
      # Keep sqlite data and uploads persisted between rebuilds
      - strapi_data:/srv/app/.tmp
      - strapi_uploads:/srv/app/public/uploads

volumes:
  web_node_modules:
  content_node_modules:
  strapi_data:
  strapi_uploads:
